# Generated by Django 5.2 on 2025-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Groceries', 'GROCERIES'), ('Clothings', 'CLOTHINGS')], max_length=15, null=True),
        ),
    ]
